### ISSUE TITLE
Exception handler

### ISSUE THREAD

**Issue by Unisay** [bellroy/wai-handler-hal#4]
Warp has this functionality to install a global exception handler:
https://hackage.haskell.org/package/warp-3.3.17/docs/Network-Wai-Handler-Warp.html#v:setOnException
or this one:
https://hackage.haskell.org/package/warp-3.3.17/docs/Network-Wai-Handler-Warp.html#v:setOnExceptionResponse

Its clear that well-behaving app handles its own exception, but in case if it doesn't its nice to have a fallback.
Also, its a good thing for app developer to have a choice on which level to handle exceptions.

**Comment by JackKelly-Bellroy** [comment]
I think that a last-resort exception handler should go into `hal` so that _something_ makes it into CloudWatch logs if all else fails, and if @iamfromspace disagrees then I'm open to considering other approaches. But I think we should aim to solve the problem at the root if at all possible.

**Comment by JackKelly-Bellroy** [comment]
@iamfromspace is happy to consider adding this to `hal`, so I'm closing this.
